### ISSUE TITLE
Referenced IDVID getting null values when meta.doctype = 'IDV'

### ISSUE THREAD

**Issue by spitfiredd** [wamuir/fpds-conversion-utility#3]
When loading data into a test database, none of the IDV's are getting a referencedIDVID

Steps to reproduct:
1. down load 7500 extract from archives [sample](https://www.fpds.gov/ddps/directory_browser/index.php?somepath=..%2FFY20-V1.5%2F7500-HEALTHANDHUMANSERVICESDEPARTMENTOF&n=4)
2. extract to folder
3.  Run `docker run -it -v ${PWD}:/tmp/data fpds-utl:1 -o tmp/data/7500-HEALTHANDHUMANSERVICESDEPARTMENTOF-IDV.xml tmp/data/test.db` in powershell on windows
4. SQL check
```
select * 
from IDVID i 
left join referencedIDVID ri 
on i.id=ri.id
where i.piid = '75FCMC20A0007'
```
5. check [fpds gov](https://www.fpds.gov/ezsearch/search.do?indexName=awardfull&templateName=1.5.1&s=FPDS.GOV&q=75FCMC20A0007)
6. Should have a referenced IDVID value of GS00F043GA
7. Open 7500-HEALTHANDHUMANSERVICESDEPARTMENTOF-IDV.xml and search for `referencedIDVID` there should be 422 out of 3965 total records referencedIDVID but the referencedIDVID table is null.

My best guess is that there is an issue in the `normalize-record.xsl` stylesheet since the column value is returning null when I do some tests in python; however the stylesheet does look right <shrug>??

**Comment by wamuir** [comment]
I think you are absolutely correct and the issue looks to be specific to Part 8 BPAs (IDV references IDV).

**Comment by spitfiredd** [comment]
Wow, I looked at those three lines of code for about 3 hours before I threw in towel and asked you for help!! Thanks a ton!
